### ISSUE TITLE
Question about the Pseudo-Labels

### ISSUE THREAD

**Issue by harukaza** [linhuixiao/CLIP-VG#12]
Thanks for your interesting work.
I have a question about the using of Pseudo-Labels. 
While I take the fully supervised training, do i need to generate the pseudo-Labels by Pseudo language label generation module?

Looking forward to your soonest reply.

**Comment by linhuixiao** [comment]
@harukaza 
Hi, pseudo-labels are only used in the unsupervised setting, and I have provided the good pseudo-labels generated by the pseudo-label generation module so that you can use them directly without having to run the generation code. Additionally, to train in a fully supervised setting, you just need to use the manual text annotations and add the training flag `--sup_type full` in the training script.

**Comment by harukaza** [comment]
Thank you for your reply. 
We would employ this model into another dataset rather than the traditional VG dataset with the full supervised setting. Then I will try the training without the pseudo-labels.
Thanks again.
